version: 2.7build{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
cache:
  - externals -> PCbuild\*
build_script:
- cmd: PCbuild\build.bat -e
- cmd: PCbuild\python.exe -m test.pythoninfo
test_script:
- cmd: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest -j2
environment:
  HOST_PYTHON: C:\Python36\python.exe
