# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: 'Hosted Ubuntu 1604'

trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
  paths:
    exclude:
    - Doc/*
    - Tools/*

#variables:


steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: ./.vsts/install_deps.sh
  displayName: 'Install dependencies'

- script: ./configure --with-pydebug
  displayName: 'Configure CPython (debug)'

- script: make -s -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: xvfb-run make buildbottest TESTOPTS="-j4 -uall,-cpu"
  displayName: 'Tests'
