# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted macOS Preview

trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
  paths:
    exclude:
    - Doc/*
    - Tools/*

#variables:

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: |
   git fetch -q origin $(system.pullRequest.targetBranch)
   changes = $(git diff --name-only HEAD $(git merge-base HEAD FETCH_HEAD))
   echo "Files changed:"
   echo "$changes"
   if ! echo "$changes" | grep -qvE '(\.rst$)|(^Doc)|(^Misc)'
   then
     echo "Only docs were updated, stopping build process."
     echo "##vso[task.setvariable variable=DocOnly]true"
     exit
   fi
  displayName: Detect doc-only changes
  condition: and(succeeded(), variables['system.pullRequest.targetBranch'])

- script: ./configure --with-pydebug --with-openssl=/usr/local/opt/openssl --prefix=/opt/python-vsts
  displayName: 'Configure CPython (debug)'
  condition: and(succeeded(), ne(variables['DocOnly'], 'true'))

- script: make -s -j4
  displayName: 'Build CPython'
  condition: and(succeeded(), ne(variables['DocOnly'], 'true'))

- script: make pythoninfo
  displayName: 'Display build info'
  condition: and(succeeded(), ne(variables['DocOnly'], 'true'))

- script: make buildbottest TESTOPTS="-j4 -uall,-cpu"
  displayName: 'Tests'
  condition: and(succeeded(), ne(variables['DocOnly'], 'true'))
